language: python
python:
  - "3.9"
cache: pip
install:
  - pip install -r requirements.txt
branches:
  except: development
  only: main
script: python --version
before_deploy:
  - rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install faraday -v 1.8.0
deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: larioshyn-fast-api
  on:
    branch: main